### ISSUE TITLE
Failure during startup of new installation

### ISSUE THREAD

**Issue by blankensteiner** [ConfigHubPub/ConfigHubPlatform#113]
Hi

I want to do a POC on ConfigHub (we are implementing OpenShift and is in that regard looking into replacing Octopus with ConfigHub), but sadly I got stuck at the installation/setup. I've created this docker-compose.yml:

```
version: '3.1'

services:
    confighub:
        image: confighub/confighubplatform:latest
        container_name: confighub
        environment:
            - DB_URL=jdbc:postgresql://postgres:5432/confighub
            - DB_DRIVER=org.postgresql.Driver
            - DB_USERNAME=someUsername
            - DB_PASSWORD=somePassword
        depends_on:
            - "postgres"
        ports:
            - 8080:80
            - 8443:443
        networks:
            - confighub
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=someUsername
            - POSTGRES_PASSWORD=somePassword
        networks:
            - confighub
networks:
    confighub:
        driver: bridge
```

I get this error from the confighub container:

> Jan 21, 2020 9:28:53 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Jan 21, 2020 9:28:53 AM org.apache.catalina.core.StandardContext startInternal

And in the log file I see:

> 2020-01-21 09:28:52,787 INFO HHH000248: Starting query cache at region: org.hibernate.cache.internal.StandardQueryCache
2020-01-21 09:28:53,040 INFO HHH000397: Using ASTQueryTranslatorFactory
2020-01-21 09:28:53,232 WARN SQL Error: 0, SQLState: 42P01
2020-01-21 09:28:53,232 ERROR ERROR: relation "systemconfig" does not exist
  Position: 239
2020-01-21 09:28:53,245 INFO ConfigHub Version: 1.8.1
2020-01-21 09:28:53,280 INFO ConfigHub Shutdown

I also wonder why it says it's 1.8.1, shouldn't it be 1.8.3?

It there a "from start to finish" setup guide for at ConfigHub newbie?
