### ISSUE TITLE
Docker usage issue

### ISSUE THREAD

**Issue by gslongo** [ConfigHubPub/ConfigHubPlatform#147]
Hi,

I tried the following docker-compose.yml file to use the ConfigHub using docker. Everything start but and ConfigHub is listening on http ports, however i get blank page (no source inside) and nothing in the log. Can you help ?

Thank you !!

```
version: "3"
services:
  confighub:
    image: confighub/confighubplatform:latest
    depends_on:
      - dbmysql
    links:
      - dbmysql
    environment:
      - DB_URL=jdbc:mysql://dbmysql:3306/ConfigHub
      - DB_DRIVER=com.mysql.jdbc.Driver
      - DB_USERNAME=root
      - DB_PASSWORD=SecretPassword
    ports:
      - "8082:80"
      - "8443:443"
  dbmysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_USER=confighub
      - MARIADB_ROOT_PASSWORD=SecretPassword
      - MARIADB_DATABASE=ConfigHub 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
    depends_on:
      - dbmysql
```
