### ISSUE TITLE
Is there a docker instance available?

### ISSUE THREAD

**Issue by aram535** [ConfigHubPub/ConfigHubPlatform#30]
It would be great to have a docker instance available with a volume map of the data directory.

**Comment by edoarsla** [comment]
Its in the works.  I expect it will be available within a couple of weeks.

**Comment by aram535** [comment]
This is great news, I tried it a couple of times but it just doesn't want to cooperate nicely.   Haven't had to force it yet.

**Comment by GroovyCarrot** [comment]
I seem to be having issues dockerising this too. I've set up a quick image, it boots up fine allows you to create an account. However, when you try to add a repository it throws the error:
```
Repository name is already used in this account
```
The Repositories table is empty, the database connection is definitely working as it has set up the tables, and created the account. This perhaps feels like an implementation bug, rather than an infrastructure issue?

You're welcome to try the image out: https://hub.docker.com/r/groovycarrot/confighub/

A quick `docker-compose.yml` to spin it up:
```
version: '3'
services:
    confighub:
        image: groovycarrot/confighub:1.6
        environment:
            DB_USERNAME: root
            DB_PASSWORD: SomeRootPassword
        ports:
          - 8080:80

    mysql:
        build: ./docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: SomeRootPassword
        networks:
            default: { aliases: ['db'] }
```
The MySQL `Dockerfile`, will need databases creating:
```
FROM        mysql:5.7
RUN         echo "CREATE DATABASE ConfigHubMain; CREATE DATABASE ConfigHubClientRequests;" > /docker-entrypoint-initdb.d/setup.sql
```

Any pointers on missing packages, or investigation into the error is appreciated.
