### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by krystofurr** [ConfigHubPub/ConfigHubPlatform#88]
Hello,

   Recently I have tried to setup ConfigHub through a docker container as well as using the download package of ConfigHub.  In both instances, I cannot get either to create the schema in the database.  I can create the database itself without issue and can also create tables using the user that is assigned in the tomee.xml file.  I had followed the installation steps through the documentation.  Is there a common pitfall or something I am missing?  I attached a docker-compose file I am using for clarification.

```yaml
version: '2.1'

networks:
    confighub_net:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1
services:
    confighub:
        networks:
            confighub_net:
                ipv4_address: 172.16.238.10
        environment:
            DB_URL: jdbc:mysql://172.16.238.11:3306/ConfigHub
            DB_DRIVER: com.mysql.jdbc.Driver
            DB_USERNAME: confighub
            DB_PASSWORD: confighub
            ALLOCATED_MEMORY: 2g
            HTTP_PORT: 9090
        image: confighub/confighubplatform:latest
        ports:
            - "9090:80"
        depends_on:
            confighub-mysql:
                condition: service_healthy
        links:
            - confighub-mysql
    confighub-mysql:
        networks:
            confighub_net:
                ipv4_address: 172.16.238.11
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 3
        environment:
            MYSQL_USER: confighub
            MYSQL_PASSWORD: confighub
            MYSQL_DATABASE: ConfigHub
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        image: mysql:5.7.23
        ports:
            - "3306:3306"
```

**Comment by edoarsla** [comment]
Hey there. You need to use the database migration tool - https://github.com/ConfigHubPub/Database-Manager

As of the last release database is liquibase managed. This is a temporary measure until we convert to SpringBoot and incorporate it all into a single package.

**Comment by krystofurr** [comment]
Ah, I see!  Thanks very much.  I had come across that, but wasn't 100% sure that I needed to use it.

**Comment by krystofurr** [comment]
If anyone is interested in a docker-compose that will pull in the database migrator and execute it against the database, here is my .yml file.  It still needs work.

```yaml
version: '2.3'

networks:
    confighub_net:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1
services:
    confighub:
        networks:
            confighub_net:
                ipv4_address: 172.16.238.10
        environment:
            DB_URL: jdbc:mysql://172.16.238.11:3306/ConfigHub
            DB_DRIVER: com.mysql.jdbc.Driver
            DB_USERNAME: confighub
            DB_PASSWORD: confighub
            ALLOCATED_MEMORY: 4g
            HTTP_PORT: 80
            HTTPS_PORT: 443
            LOG_PATH: /var/log/confighub
            KEYSTORE_FILE: cert/confighub_default.jks
            KEYSTORE_ALIAS: confighub
            KEYSTORE_PASSWORD: confighub
        image: confighub/confighubplatform:latest
        depends_on:
            confighub-mysql:
                condition: service_healthy
            confighub-db-manager:
                condition: service_healthy
        links:
            - confighub-mysql
        ports:
            - "9090:80"
    confighub-db-manager:
        networks:
            confighub_net:
                ipv4_address: 172.16.238.12
        depends_on:
            confighub-mysql:
                condition: service_healthy
        healthcheck:
            test: find -name "confighub-db-manager-completed" | grep -q "."
            timeout: 30s
            retries: 10
            start_period: 1m
        build:
            context: ./db-manager
            args:
                REPO: https://github.com/ConfigHubPub/Database-Manager.git
        command: [sh, -c, "java -jar build/libs/ConfigHubDBManager-1.8.jar -t=mysql -r=jdbc:mysql://172.16.238.11:3306/ConfigHub -u=confighub -p=confighub && touch confighub-db-manager-completed && tail -f /dev/null"]
    confighub-mysql:
        networks:
            confighub_net:
                ipv4_address: 172.16.238.11
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 3
        environment:
            MYSQL_USER: confighub
            MYSQL_PASSWORD: confighub
            MYSQL_DATABASE: ConfigHub
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        image: mysql:5.7.23
        ports:
            - "3306:3306"
```
